apiVersion: v1
kind: ConfigMap
metadata:
  name: typescript-app-config
  namespace: typescript-namespace
  labels:
    app: typescript-app
    environment: production
data:
  # Application configuration
  NODE_ENV: "production"
  PORT: "8080"
  LOG_LEVEL: "info"
  
  # Security configuration
  NODE_OPTIONS: "--max-old-space-size=1024 --max-http-header-size=8192"
  NPM_CONFIG_AUDIT_LEVEL: "high"
  NPM_CONFIG_FUND: "false"
  NPM_CONFIG_UPDATE_NOTIFIER: "false"
  
  # Application specific settings
  APP_NAME: "typescript-application"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  
  # Health check configuration
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_TIMEOUT: "5000"
  
  # Security headers
  ENABLE_SECURITY_HEADERS: "true"
  CORS_ENABLED: "true"
  RATE_LIMIT_ENABLED: "true"
