apiVersion: v1
kind: Secret
metadata:
  name: typescript-app-secrets
  namespace: typescript-namespace
  labels:
    app: typescript-app
    environment: production
type: Opaque
data:
  # Database connection (base64 encoded placeholder - replace with actual values)
  DB_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  JWT_SECRET: cGxhY2Vob2xkZXI=   # placeholder
  API_KEY: cGxhY2Vob2xkZXI=     # placeholder
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: typescript-app-sa
  namespace: typescript-namespace
  labels:
    app: typescript-app
    environment: production
  annotations:
    description: "Service account for TypeScript application"
automountServiceAccountToken: false
